FROM ubuntu:latest

RUN apt update
RUN apt upgrade -y
RUN apt-get install -y gcc
RUN apt-get install -y g++
RUN apt-get install -y build-essential cmake bash-completion cmake-extras git vim nano



SHELL [ "/bin/bash" ]